name: java
on:
  push:
    paths:
      - '**'
  pull_request:
    branches:
      - main
    types:
      - opened
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
<<<<<<< HEAD
      - name: Set up JDK 11
=======
      - name: set up JDK 17
>>>>>>> branch 'v033_11' of git@github.com:datahaki/bridge.git
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: mvn install tensor
        working-directory: .
        run: |
          cd ..
          git clone https://github.com/datahaki/tensor.git
          cd tensor
          git checkout v106
          mvn clean install -DskipTests=true
      - name: mvn test
        working-directory: .
        run: xvfb-run --auto-servernum mvn test -B
