name: java
on:
  push:
    paths:
      - '**'
  pull_request:
    branches:
      - main
    types:
      - opened
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: set up env
        run: sudo apt-get install xvfb
      - name: mvn install tensor
        working-directory: .
        run: |
          cd ..
          git clone https://github.com/datahaki/tensor.git
          cd tensor
          pwd
          git checkout v106
          mvn clean install -DskipTests=true
      - name: mvn test
        working-directory: .
        run: |
          pwd
          xvfb-run --auto-servernum mvn test -B
