name: mvn test using JDK 11
on:
  push:
    paths:
      - '**'
  pull_request:
    branches:
      - main
    types:
      - opened
jobs:
  os_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: mvn install tensor
        working-directory: .
        run: |
          cd ..
          git clone https://github.com/datahaki/tensor.git
          cd tensor
          git checkout v107_11
          mvn clean install -DskipTests=true
      - name: mvn test
        working-directory: .
        run: xvfb-run --auto-servernum mvn test -B
