name: java
on:
  push:
    paths:
      - '**'
  pull_request:
    branches:
      - main
    types:
      - opened
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Set up env
        run: sudo apt-get install xvfb
      - name: Install tensor 106
        working-directory: .
        run:
          mkdir tmp
          cd tmp
          git clone https://github.com/datahaki/tensor.git
          cd tensor
          git checkout v106
          mvn clean install -DskipTests=true
      - name: mvn install
        working-directory: .
        run: xvfb-run --auto-servernum mvn install -B
